# config-groups:
#   default:
#     param1:
#       label: First parameter
#       mandatory: true
#       default: test
#       type: single
#       visible: true
#       validator: '[A-z\._]+'
#       help: This is just a testing parameter
